#!/bin/bash

JAR_GLOB="target/amen-data-processing-*-uber.jar"
JAR=`ls $JAR_GLOB`

echo "Using jar: $JAR"
if [ ! -f "$JAR" ]; then
  echo "jar file not found: $JAR_GLOB"
  exit 1
fi

java -cp $HADOOP_HOME_/hadoop-core-0.20.205.0.jar:$HADOOP_HOME_/conf:$PIG_HOME/pig-0.9.1-withouthadoop.jar:$JAR org.apache.pig.Main -l target/log $@

